set_property PACKAGE_PIN AN38 [get_ports clk_in1_p]
set_property IOSTANDARD  LVDS [get_ports clk_in1_p]
create_clock -period 8 -name clk_in1_p [get_ports clk_in1_p]

set_property PACKAGE_PIN AN39 [get_ports clk_in1_n]
set_property IOSTANDARD  LVDS [get_ports clk_in1_n]
create_clock -period 8 -name clk_in1_n [get_ports clk_in1_n]

set_property PACKAGE_PIN AP39 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]

##//----------------------------------------------------------------------------
##//--rs 485
##//----------------------------------------------------------------------------
set_property PACKAGE_PIN AU25 [get_ports RS485_3_CLK_DE_18]
set_property PACKAGE_PIN AU26 [get_ports RS485_3_CLK_D_18]  
set_property PACKAGE_PIN AU27 [get_ports RS485_3_CLK_PV_18]
set_property PACKAGE_PIN AU28 [get_ports RS485_3_CLK_RE_18] 

 
set_property IOSTANDARD LVCMOS18 [get_ports RS485_3_CLK_DE_18]
set_property IOSTANDARD LVCMOS18 [get_ports RS485_3_CLK_PV_18]
set_property IOSTANDARD LVCMOS18 [get_ports RS485_3_CLK_D_18] 
set_property IOSTANDARD LVCMOS18 [get_ports RS485_3_CLK_RE_18]

set_property PACKAGE_PIN AM27 [get_ports RS485_4_CLK_DE_18]
set_property PACKAGE_PIN BD27 [get_ports RS485_4_CLK_PV_18]
set_property PACKAGE_PIN BD25 [get_ports RS485_4_CLK_RE_18] 
set_property PACKAGE_PIN BC25 [get_ports RS485_4_CLK_R_18]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets RS485_4_CLK_R_18_IBUF]
  
set_property IOSTANDARD LVCMOS18 [get_ports RS485_4_CLK_DE_18]
set_property IOSTANDARD LVCMOS18 [get_ports RS485_4_CLK_PV_18]
set_property IOSTANDARD LVCMOS18 [get_ports RS485_4_CLK_RE_18] 
set_property IOSTANDARD LVCMOS18 [get_ports RS485_4_CLK_R_18]

set_property PACKAGE_PIN AT26 [get_ports RS485_3_DE_18]
set_property PACKAGE_PIN AR28 [get_ports RS485_3_PV_18]
set_property PACKAGE_PIN AR27 [get_ports RS485_3_D_18] 
set_property PACKAGE_PIN AR26 [get_ports RS485_3_RE_18]
 
set_property IOSTANDARD LVCMOS18 [get_ports RS485_3_DE_18]
set_property IOSTANDARD LVCMOS18 [get_ports RS485_3_PV_18]
set_property IOSTANDARD LVCMOS18 [get_ports RS485_3_D_18] 
set_property IOSTANDARD LVCMOS18 [get_ports RS485_3_RE_18]

set_property PACKAGE_PIN BC27 [get_ports RS485_4_DE_18]
set_property PACKAGE_PIN BB27 [get_ports RS485_4_PV_18]
set_property PACKAGE_PIN BB26 [get_ports RS485_4_R_18] 
set_property PACKAGE_PIN BA25 [get_ports RS485_4_RE_18]
 
set_property IOSTANDARD LVCMOS18 [get_ports RS485_4_DE_18]
set_property IOSTANDARD LVCMOS18 [get_ports RS485_4_PV_18]
set_property IOSTANDARD LVCMOS18 [get_ports RS485_4_R_18] 
set_property IOSTANDARD LVCMOS18 [get_ports RS485_4_RE_18]


set_property PACKAGE_PIN AL20 [get_ports {DSP_EMIFA[0]}]
set_property PACKAGE_PIN AL19 [get_ports {DSP_EMIFA[1]}]
set_property PACKAGE_PIN BC20 [get_ports {DSP_EMIFA[2]}]
set_property PACKAGE_PIN AL18 [get_ports {DSP_EMIFA[3]}]
set_property PACKAGE_PIN BD20 [get_ports {DSP_EMIFA[4]}]
set_property PACKAGE_PIN BC19 [get_ports {DSP_EMIFA[5]}]
set_property PACKAGE_PIN AW21 [get_ports {DSP_EMIFA[6]}]
set_property PACKAGE_PIN AK17 [get_ports {DSP_EMIFA[7]}]
set_property PACKAGE_PIN AM18 [get_ports {DSP_EMIFA[8]}]
set_property PACKAGE_PIN AN17 [get_ports {DSP_EMIFA[9]}]
set_property PACKAGE_PIN BD21 [get_ports {DSP_EMIFA[10]}]
set_property PACKAGE_PIN BB21 [get_ports {DSP_EMIFA[11]}]
set_property PACKAGE_PIN AY21 [get_ports {DSP_EMIFA[12]}]
set_property PACKAGE_PIN BC18 [get_ports {DSP_EMIFA[13]}]
set_property PACKAGE_PIN BD19 [get_ports {DSP_EMIFA[14]}]
set_property PACKAGE_PIN AN19 [get_ports {DSP_EMIFA[15]}]
set_property PACKAGE_PIN AM20 [get_ports {DSP_EMIFA[16]}]
set_property PACKAGE_PIN AP19 [get_ports {DSP_EMIFA[17]}]
set_property PACKAGE_PIN BA21 [get_ports {DSP_EMIFA[18]}]
set_property PACKAGE_PIN BB18 [get_ports {DSP_EMIFA[19]}]
set_property PACKAGE_PIN BB20 [get_ports {DSP_EMIFA[20]}]
set_property PACKAGE_PIN AR18 [get_ports {DSP_EMIFA[21]}]
set_property PACKAGE_PIN AT20 [get_ports {DSP_EMIFA[22]}]
set_property PACKAGE_PIN AJ17 [get_ports {DSP_EMIFA[23]}]
set_property PACKAGE_PIN AT19 [get_ports {DSP_EMIFBE0_N}]
set_property PACKAGE_PIN AH20 [get_ports {DSP_EMIFBE1_N}]
set_property PACKAGE_PIN AJ19 [get_ports {DSP_EMIFCE0_N}]
set_property PACKAGE_PIN AK18 [get_ports {DSP_EMIFOE_N}]
set_property PACKAGE_PIN AK19 [get_ports {DSP_EMIFRW_N}]
set_property PACKAGE_PIN AN20 [get_ports {DSP_EMIFWAIT0}]
set_property PACKAGE_PIN AN18 [get_ports {DSP_EMIFWAIT1}]

set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFA[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFBE0_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFBE1_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFCE0_N}]
set_property IOSTANDARD LVDCI_18 [get_ports {DSP_EMIFOE_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFD[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFRW_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFWAIT0}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFWAIT1}]
set_property IOSTANDARD LVCMOS18 [get_ports {DSP_EMIFWE_N}]

set_property PACKAGE_PIN AJ20 [get_ports {DSP_EMIFWE_N}]
set_property PACKAGE_PIN AP20 [get_ports {DSP_EMIFD[0]}]
set_property PACKAGE_PIN AU18 [get_ports {DSP_EMIFD[1]}]
set_property PACKAGE_PIN AT18 [get_ports {DSP_EMIFD[2]}]
set_property PACKAGE_PIN AR19 [get_ports {DSP_EMIFD[3]}]
set_property PACKAGE_PIN AH19 [get_ports {DSP_EMIFD[4]}]
set_property PACKAGE_PIN AU20 [get_ports {DSP_EMIFD[5]}]
set_property PACKAGE_PIN AV20 [get_ports {DSP_EMIFD[6]}]
set_property PACKAGE_PIN AY18 [get_ports {DSP_EMIFD[7]}]
set_property PACKAGE_PIN AV19 [get_ports {DSP_EMIFD[8]}]
set_property PACKAGE_PIN AW19 [get_ports {DSP_EMIFD[9]}]
set_property PACKAGE_PIN BA20 [get_ports {DSP_EMIFD[10]}]
set_property PACKAGE_PIN BA19 [get_ports {DSP_EMIFD[11]}]
set_property PACKAGE_PIN BA18 [get_ports {DSP_EMIFD[12]}]
set_property PACKAGE_PIN AY19 [get_ports {DSP_EMIFD[13]}]
set_property PACKAGE_PIN AV18 [get_ports {DSP_EMIFD[14]}]
set_property PACKAGE_PIN AW20 [get_ports {DSP_EMIFD[15]}]
##//----------------------------------------------------------------------------
##//--dsp relative signal
##//----------------------------------------------------------------------------

set_property PACKAGE_PIN AV38 [get_ports {dsp0_lresetnmien_n}]
set_property PACKAGE_PIN AU37 [get_ports {rst_c6678_por_n}]
set_property PACKAGE_PIN AP34 [get_ports {rst_c6678_full_n}]
set_property PACKAGE_PIN AU35 [get_ports {dsp0_coresel0}]
set_property PACKAGE_PIN AT35 [get_ports {dsp0_coresel1}]
set_property PACKAGE_PIN AR36 [get_ports {dsp0_coresel2}]
set_property PACKAGE_PIN AP36 [get_ports {dsp0_coresel3}]
set_property PACKAGE_PIN N18 [get_ports {dsp0_timi0}]
set_property PACKAGE_PIN N17 [get_ports {dsp0_timi1}]
set_property PACKAGE_PIN AW36 [get_ports {rst_c6678_soft_n}]
set_property PACKAGE_PIN AV37 [get_ports {rst_c6678_local_n}]
set_property PACKAGE_PIN AR32 [get_ports {endian_dsp0 }]
set_property PACKAGE_PIN AP32 [get_ports {boot_strap0_1}]
set_property PACKAGE_PIN AR33 [get_ports {boot_strap0_2}]
set_property PACKAGE_PIN AV33 [get_ports {boot_strap0_3}]
set_property PACKAGE_PIN AT33 [get_ports {boot_strap0_4}]
set_property PACKAGE_PIN AT34 [get_ports {boot_strap0_5}]
set_property PACKAGE_PIN AU33 [get_ports {boot_strap0_6}]
set_property PACKAGE_PIN AU32 [get_ports {boot_strap0_7}]
set_property PACKAGE_PIN AV34 [get_ports {boot_strap0_8}]
set_property PACKAGE_PIN AR34 [get_ports {boot_strap0_9}]
set_property PACKAGE_PIN BB33 [get_ports {boot_strap0_10}]
set_property PACKAGE_PIN BC33 [get_ports {boot_strap0_11}]
set_property PACKAGE_PIN BB35 [get_ports {boot_strap0_12}]
set_property PACKAGE_PIN BC35 [get_ports {boot_strap0_13}]
set_property PACKAGE_PIN AY33 [get_ports {boot_strap0_14}]
set_property PACKAGE_PIN BA33 [get_ports {boot_strap0_15}]

set_property PACKAGE_PIN AJ29 [get_ports {dsp_led_0}]

set_property IOSTANDARD LVCMOS18 [get_ports {dsp_led_0}]
set_property IOSTANDARD LVCMOS18 [get_ports {dsp0_lresetnmien_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {rst_c6678_soft_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {rst_c6678_local_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {rst_c6678_por_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {rst_c6678_full_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {dsp0_coresel0}]
set_property IOSTANDARD LVCMOS18 [get_ports {dsp0_coresel1}]
set_property IOSTANDARD LVCMOS18 [get_ports {dsp0_coresel2}]
set_property IOSTANDARD LVCMOS18 [get_ports {dsp0_coresel3}]

set_property IOSTANDARD LVCMOS18 [get_ports {dsp0_timi0}]
set_property IOSTANDARD LVCMOS18 [get_ports {dsp0_timi1}]
set_property IOSTANDARD LVCMOS18 [get_ports {endian_dsp0}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_1}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_2}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_3}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_4}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_5}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_6}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_7}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_8}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_9}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_10}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_11}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_12}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_13}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_14}]
set_property IOSTANDARD LVCMOS18 [get_ports {boot_strap0_15}]
##//----------------------------------------------------------------------------
##//--others
##//----------------------------------------------------------------------------
##//----------------------------------------------------------------------------
##//--END

